Models/Aluno.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Exerc_Alunos.Models
{
    [Table("alunos")]
    public class Aluno
    {
        [Key]
        public int id { get; set; }

        [Display(Name ="Nome:")]
        public string Nome { get; set; }


        [Display(Name = "Endereço")]
        public string endereco { get; set; }


        [Display(Name = "cpf")]
        public string cpf { get; set; }


        [Display(Name = "telefone")]
        public string telefone { get; set; }


        [Display(Name = "Materia:")]
        public string materia { get; set; }









    }
}

Models/ErrorViewModel.cs
using System;

namespace Exerc_Alunos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AlunoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Exerc_Alunos.Data;
using Exerc_Alunos.Models;

namespace Exerc_Alunos.Controllers
{
    public class AlunoesController : Controller
    {
        private readonly DataContext _context;

        public AlunoesController(DataContext context)
        {
            _context = context;
        }

        // GET: Alunoes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Alunos.ToListAsync());
        }

        // GET: Alunoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aluno = await _context.Alunos
                .FirstOrDefaultAsync(m => m.id == id);
            if (aluno == null)
            {
                return NotFound();
            }

            return View(aluno);
        }

        // GET: Alunoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Alunoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Nome,endereco,cpf,telefone,materia")] Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aluno);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aluno);
        }

        // GET: Alunoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aluno = await _context.Alunos.FindAsync(id);
            if (aluno == null)
            {
                return NotFound();
            }
            return View(aluno);
        }

        // POST: Alunoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Nome,endereco,cpf,telefone,materia")] Aluno aluno)
        {
            if (id != aluno.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aluno);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlunoExists(aluno.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aluno);
        }

        // GET: Alunoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aluno = await _context.Alunos
                .FirstOrDefaultAsync(m => m.id == id);
            if (aluno == null)
            {
                return NotFound();
            }

            return View(aluno);
        }

        // POST: Alunoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aluno = await _context.Alunos.FindAsync(id);
            _context.Alunos.Remove(aluno);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AlunoExists(int id)
        {
            return _context.Alunos.Any(e => e.id == id);
        }
    }
}

Controllers/HomeController.cs
using Exerc_Alunos.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Exerc_Alunos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Alunoes/Create.cshtml
@model Exerc_Alunos.Models.Aluno

@{
    ViewData["Title"] = "Cadastrar Aluno";
}

<h1>Cadastrar</h1>

<h4>Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="endereco" class="control-label"></label>
                <input asp-for="endereco" class="form-control" />
                <span asp-validation-for="endereco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cpf" class="control-label"></label>
                <input asp-for="cpf" class="form-control" />
                <span asp-validation-for="cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefone" class="control-label"></label>
                <input asp-for="telefone" class="form-control" />
                <span asp-validation-for="telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="materia" class="control-label"></label>
                <input asp-for="materia" class="form-control" />
                <span asp-validation-for="materia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Alunoes/Delete.cshtml
@model Exerc_Alunos.Models.Aluno

@{
    ViewData["Title"] = "Apagar";
}

<h1>Apagar</h1>

<h3>Deseja apagar?</h3>
<div>
    <h4>Aluno</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.endereco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.endereco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cpf)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cpf)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.materia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.materia)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

Views/Alunoes/Details.cshtml
@model Exerc_Alunos.Models.Aluno

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes</h1>

<div>
    <h4>Aluno</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.endereco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.endereco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.cpf)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.cpf)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.materia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.materia)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Editar</a> |
    <a asp-action="Index">voltar</a>
</div>

Views/Alunoes/Edit.cshtml
@model Exerc_Alunos.Models.Aluno

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Aluno</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="endereco" class="control-label"></label>
                <input asp-for="endereco" class="form-control" />
                <span asp-validation-for="endereco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cpf" class="control-label"></label>
                <input asp-for="cpf" class="form-control" />
                <span asp-validation-for="cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefone" class="control-label"></label>
                <input asp-for="telefone" class="form-control" />
                <span asp-validation-for="telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="materia" class="control-label"></label>
                <input asp-for="materia" class="form-control" />
                <span asp-validation-for="materia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Alunoes/Index.cshtml
@model IEnumerable<Exerc_Alunos.Models.Aluno>

@{
    ViewData["Title"] = "Index";
}

<h1>Listar</h1>

<p>
    <a asp-action="Create">Cadastrar Novo Aluno</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.endereco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.materia)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.endereco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cpf)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.materia)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Apagar</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Exerc_Alunos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Alunoes" asp-action="Index">Alunos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Danilo Repas Pinha - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>